# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import client_pb2 as client__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class ClientServiceStub(object):
  """Service provided by client machine.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.DisplayMessage = channel.unary_unary(
        '/flightlab.ClientService/DisplayMessage',
        request_serializer=client__pb2.Message.SerializeToString,
        response_deserializer=client__pb2.GeneralResponse.FromString,
        )
    self.DisplayImage = channel.unary_unary(
        '/flightlab.ClientService/DisplayImage',
        request_serializer=client__pb2.Image.SerializeToString,
        response_deserializer=client__pb2.GeneralResponse.FromString,
        )
    self.DisplayOff = channel.unary_unary(
        '/flightlab.ClientService/DisplayOff',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=client__pb2.GeneralResponse.FromString,
        )


class ClientServiceServicer(object):
  """Service provided by client machine.
  """

  def DisplayMessage(self, request, context):
    """Displays a text message.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DisplayImage(self, request, context):
    """Displays an image.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DisplayOff(self, request, context):
    """Turns off display.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ClientServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'DisplayMessage': grpc.unary_unary_rpc_method_handler(
          servicer.DisplayMessage,
          request_deserializer=client__pb2.Message.FromString,
          response_serializer=client__pb2.GeneralResponse.SerializeToString,
      ),
      'DisplayImage': grpc.unary_unary_rpc_method_handler(
          servicer.DisplayImage,
          request_deserializer=client__pb2.Image.FromString,
          response_serializer=client__pb2.GeneralResponse.SerializeToString,
      ),
      'DisplayOff': grpc.unary_unary_rpc_method_handler(
          servicer.DisplayOff,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=client__pb2.GeneralResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'flightlab.ClientService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
